# Test your FastAPI endpoints

GET http://127.0.0.1:8000/csv
Accept: application/json

###

GET http://127.0.0.1:8000/hasan
Accept: application/json

###

GET http://127.0.0.1:8000/while/3
Accept: application/json

###

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/start_schedule/download_volume_15m
Accept: application/json

###

GET http://127.0.0.1:8000/schedule/show_schedules/
Accept: application/json

###

GET http://127.0.0.1:8000/del_schedule/download_volume_15m
Accept: application/json