POST http://127.0.0.1:8000/luna
Content-Type: application/json

{
   "symbol":"SHIBBUSD",
   "tv_price":"82.77",
   "timeframe":"S",
   "side":"buy",
   "alert_algo":"heikin_benimki"
}

###
POST https://csvfastapi.mamacita-fashion.com/app/luna
Content-Type: application/json

{
   "symbol":"LUNABUSD",
   "tv_price":"82.77",
   "timeframe":"S",
   "side":"sell",
   "alert_algo":"heikin_benimki"
}

###
POST http://127.0.0.1:8000/tv_signals
Content-Type: application/json

{
  "symbol": "COCOSUSDT",
  "tv_price": "1.377",
  "rsi": "32.35",
  "tsi": "-31.91",
  "adx": "42.2",
  "rvol": "4.84",
  "supertrend": "Down",
  "timeframe": "15",
  "side": "buy",
  "alert_algo": "rvol"
}

###

POST https://csvfastapi.mamacita-fashion.com/app/tv_signals
Content-Type: application/json

{
  "symbol": "COCOSUSDT",
  "tv_price": "1.377",
  "rsi": "32.35",
  "tsi": "-31.91",
  "adx": "42.2",
  "rvol": "4.84",
  "supertrend": "Down",
  "timeframe": "5",
  "side": "buy",
  "alert_algo": "rvol"
}

###

GET http://127.0.0.1:8000/cache_test
Content-Type: application/json

{
   "symbol":"BNBBUSD",
   "tv_price":"82.77",
   "timeframe":"S",
   "side":"sell",
   "alert_algo":"heikin_benimki"
}